-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Oct 03, 2019 at 03:18 PM
-- Server version: 8.0.11
-- PHP Version: 7.1.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `SS_netstrat442`
--

-- --------------------------------------------------------

--
-- Table structure for table `ArticlePage`
--

CREATE TABLE `ArticlePage_Live` (
  `ID` int(11) NOT NULL,
  `Date` date DEFAULT NULL,
  `Teaser` mediumtext,
  `Pullquote` mediumtext,
  `Author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Email` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `PhotoID` int(11) NOT NULL DEFAULT '0',
  `Writer` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `ArticlePage`
--

INSERT INTO `ArticlePage_Live` (`ID`, `Date`, `Teaser`, `Pullquote`, `Author`, `Email`, `PhotoID`, `Writer`) VALUES
(16, '2015-11-10', NULL, 'Fixed broadband affordability has improved in all our sample countries, but even a low-level use of 2GB per month requires more than 100% of average monthly income in both Papua New Guinea and the Solomon Islands.', 'Nina Matthews', 'n.matthews@strategies.nzl.com', 21, 'Nina Matthews'),
(17, '2014-09-09', NULL, 'Despite Pacific Fibre’s failure and even with the continuous upgrades of the Southern Cross Cable there is serious interest in building an additional international link for New Zealand.', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 6, 'Nicolas Tassitani'),
(18, '2014-07-08', NULL, 'The locking-in under RAB regulation prevents over- or under- recovery of costs, particularly for legacy assets, and thus promotes efficient investment decisions to provide high quality services at fair prices to the consumers.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 25, 'Suella Hansen'),
(19, '2014-04-08', NULL, '...a few regulators are adopting hybrid and innovative models to assess and incentivise quality and performance indicators for electricity regulation.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 54, 'Suella Hansen'),
(20, '2014-02-11', NULL, '…had Chorus been obligated to complete a Part 4 Information Disclosure template, the Government may have been in a far stronger position to make and / or justify its assessment for the Telecommunications Review. ', 'Suella Hansen', 's.hansen@strategies.nzl.com', 24, 'Suella Hansen'),
(21, '2014-01-28', 'The deployment of smart grids by electric utilities worldwide has provided significant benefits to the utilities as well as to the wider communities. Through the ability to deploy fibre alongside their existing networks, and vast experience in the deployment and operation of infrastructure, utilities are able to enter the telecommunications market with ease and compete fiercely with existing operators. It is therefore unsurprising that many telcos have legally challenged such utilities in an attempt to stamp out or delay competition.', '…these utilities also contribute in bridging the digital divide by delivering affordable access to fast broadband services in their service areas.', 'Suella Hansen', NULL, 28, 'Suella Hansen'),
(22, '2014-01-13', NULL, '…the town will attract new businesses and talent to the area, lead in fibre services innovation and improve the quality of life of its residents faster than any other town in New Zealand.', 'Suella Hansen', NULL, 20, 'Suella Hansen'),
(25, '2013-12-09', NULL, '…operators still have stagnant or falling ARPUs, with the time since LTE was introduced not having a bearing on this result. However, the portion of revenue gained from non-voice services has been increasing', 'Nina Matthews', 'n.matthews@strategies.nzl.com', 86, 'Nina Matthews'),
(26, '2013-06-04', 'Mobile phones have been widely adopted as a tool for communication and significantly influenced the lives of people all over the world. At Network Strategies, we regularly collect data for mobile services offered in several Pacific countries and compare the prices and affordability of these services. In addition to the fifteen countries we analysed in April last year, operators from two additional countries – Timor-Leste and American Samoa – have been included in our analysis this year.', '...the affordability of mobile services differs widely across the Pacific countries. For the low volume and typical prepaid usages, American Samoa has the most affordable mobile services whereas Kiribati has least affordable services.', 'Nina Matthews', 'n.matthews@strategies.nzl.com', 88, 'Nina Matthews'),
(30, '2013-03-12', 'Around the world substantial increases in the accessibility and affordability of mobile technologies have been achieved through efficient and effective market competition. Increasingly evidence indicates that access to information communication technologies, and in particular mobile services, has a significant impact on economic growth. As a result increasing mobile penetration, affordability and therefore use is becoming important to growth and poverty reduction strategies for development.  ', 'The unique challenges of infrastructure rollout in the Pacific coupled with incumbent operators that were ill-prepared for competition meant that the new entrant has been able to rapidly acquire a large market share to the detriment of end-users. ', 'Suella Hansen', 's.hansen@strategies.nzl.com', 85, 'Suella Hansen'),
(31, '2013-02-12', NULL, 'We started Pacific Fibre because we know how important it is to connect New Zealanders to global markets. The high cost of broadband in New Zealand makes it hard to connect globally and it is this market failure, not a technical failure, that we tried hard to solve. - Rod Drury, co-founder of Pacific Fibre', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 92, 'Nicolás Tassitani'),
(32, '2013-01-29', 'Convergence has become a pervasive trend with the advent of new technologies, enabling “anytime, anywhere” access to resources. It has redefined “communication” by combining telecommunications and broadcasting sectors and offering multiple services using a single device over a single network. For example, today “watching TV”, “accessing emails” and “phone calling” can all be performed on an IP network (instead of traditionally separate networks) using a single device (like a smartphone). ', '...convergence is a positive and irreversible step that has led to significant advancements in communication services.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 89, 'Suella Hansen'),
(33, '2012-12-04', 'Following our friendly trans-Tasman comparisons of prepaid offerings for mobile voice and SMS, we have now turned our attention to mobile data. We have compared local costs for mobile broadband designed for use on a laptop or tablet, and for Internet access via a mobile handset between NZ and Australia, and found that New Zealand customers suffer with pitiful data caps for mobile broadband, whereas Australian customers who want to roam to New Zealand with their mobile handset and use data may be in for a shock when the bill comes in.', '…New Zealand customers suffer with pitiful data caps for mobile broadband... Australian customers who want to roam to New Zealand may be in for a shock...', 'Nina Matthews', 'n.matthews@strategies.nzl.com', 112, 'Nina Matthews'),
(35, '2012-09-11', NULL, 'Provision of payphones is a social obligation for many telecoms operators, but they are a high cost / low return proposition, so it is hardly surprising that operators are keen to reduce numbers and/or increase the price of calls.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 42, 'Noelle Jones'),
(60, '2012-07-10', NULL, 'The use of complementary network technologies for delivering data originally intended for cellular networks seems to be the immediate solution to cope with the rapid growth in mobile data traffic. ', 'Nicolás Tassitani', 'n.tassitani@strategies.nzl.com', 113, 'Nicolás Tassitani'),
(61, '2012-05-08', NULL, 'As the outcome hinges on the technology used, based on the current decision there is room for lengthy technical arguments in future cases to test the interests of rights holders against new technology. ', 'Noelle Jones', 'n.jones@strategies.nzl.com', 98, 'Noelle Jones'),
(64, '2011-12-06', 'Fast broadband connections have paved the way for broadcasters and telecommunications service providers to enter into each others’ markets internationally. As a result, a 2006 OECD report stated that the telecommunications industry was facing an identity crisis. The bundling of various communications services is becoming increasingly popular. Multi-service offerings may include dual play, triple-play or even quadruple-play bundled offerings. Many countries have responded by merging their broadcasting and telecommunications regulators. With UFB now in New Zealand, a hot topic is whether it should also follow this worldwide trend.', 'With evolving technology and new services, particularly in light of UFB, laws, policies and regulations will also need to evolve in order to prevent problems up-stream instead of providing the ambulance at the bottom of the cliff.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 114, 'Suella Hansen'),
(66, '2011-03-09', NULL, 'Hydro-trenching clearly offers a cost-effective and minimally invasive solution for deploying networks, particularly in urban areas where suitable pipes are available.', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 99, 'Nicolás Tassitani'),
(69, '2010-12-14', NULL, 'The increasing number of digital music stores where consumers are able to purchase legal copies of digital media for their personal use means that users may be paying twice for content through the imposition of such a levy.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 97, 'Noelle Jones'),
(71, '2010-08-03', NULL, 'one school of thought suggests that sharing might be the way to go in New Zealand for economical rollout. Operators would potentially share infrastructure, cell sites and even spectrum, so that we have just one nationwide LTE network.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 133, 'Suella Hansen'),
(72, '2010-07-27', NULL, 'mobile broadband is very much cheaper in Norway than in New Zealand, so with higher incomes mobile broadband is far more affordable.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 141, 'Noelle Jones'),
(73, '2009-12-08', NULL, '…a conservative FTTH business planner might choose take-up assumptions in the region of 30%. Could utilities, on the strength of the US municipality figures, assume rates in the vicinity of 50%?', 'Suella Hansen', 's.hansen@strategies.nzl.com', 33, 'Suella Hansen'),
(74, '2009-10-13', NULL, '…the requirement to provide the open access layer 1 service will preclude some network design options', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 142, 'Nicolás Tassitani'),
(75, '2009-10-01', NULL, 'In larger countries it is often possible to justify such large budgets when they are spread over the population that is benefiting…smaller countries usually cannot make such claims, and the situation can be further exacerbated when the anticipated economic, and particularly financial, benefits are not (yet) being realised. ', 'Suella Hansen', 's.hansen@strategies.nzl.com', 86, 'Suella Hansen'),
(76, '2009-06-09', 'France has been one of the dominant forces in the global IPTV market. According to the French telecoms regulator, ARCEP, 37% of xDSL subscribers were able to access IPTV as at the end of 2008, either through subscriptions or via the triple-play bundles that are a feature of the French broadband market. The audience measurement company Mediametrie claimed that IPTV overtook cable TV in terms of subscribers in mid-2008.', 'the success of an IPTV strategy will depend on favourable market and regulatory conditions – and ultimately the ability of the operator to deliver attractive content at an affordable price ', 'Noelle Jones', 'n.jones@strategies.nzl.com', 150, 'Noelle Jones'),
(77, '2009-02-17', NULL, 'VDSL2 will not reach enough customers without significant additional investment on top of current cabinetisation plans', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 148, 'Nicolás Tassitani'),
(78, '2008-12-09', NULL, '...while micro-trenching can in principle significantly reduce the cost of deploying fibre, it cannot be used everywhere and should not be relied upon as a ubiquitous solution.', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 154, 'Nicolás Tassitani'),
(79, '2008-11-18', 'From the FTTH Council’s global rankings for FTTH penetration we can gain some insights into the thorny question of how to achieve fibre rollout in the face of a difficult cost versus revenue equation. South Korea, Hong Kong and Taiwan are the leaders in Fibre to the Building deployment with their dense urban dwellings assisting the economic case via demographic and geographic patterns. The leaders in straight FTTH deployment are Japan, Sweden, Norway, Slovenia, Iceland and Denmark where in most cases geography is less useful for the cause. So what makes the economic case workable in these countries and who are the prime movers?', '...in many of the frontrunner countries incumbent operators are coming to the party... if not leading the charge then responding competitively to proactive newcomers.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 57, 'Suella Hansen'),
(80, '2008-10-14', 'For most consumers, choosing a broadband plan is an exercise in identifying the “best” service for a given budget. While the headlines tend to focus on the downlink bandwidth – faster is better – the consumer’s purchase decision is more complex as it involves prioritising various criteria, based on individual requirements and budget. ', 'Without a doubt our best broadband option is gained by living in a fibre-installed apartment in Japan. We would be getting a symmetric 100Mbit/s service with unlimited downloads...an awesome experience at an extremely low price.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 185, 'Noelle Jones'),
(81, '2008-05-14', NULL, '…regulators need to address how the universal service should best evolve to address both market and technological developments.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 151, 'Noelle Jones'),
(82, '2008-04-15', NULL, 'Any vision of a new entrant competing with wireline broadband players would have been incredibly optimistic.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 29, 'Noelle Jones'),
(83, '2008-02-27', 'In recent weeks the social network, Facebook, has been widely criticised for the difficulties experienced by its users wishing to end their association with the site, and seeking to delete their accounts and all of their content. However, in Facebook’s November 2007 Terms of Use, to which members would have agreed in order to complete the registration process, it is clearly stated that although “you may remove your User Content from the Site at any time”, “you acknowledge that the Company may retain archived copies of your User Content”. ', '… In today’s society where the currency is information, and national policies are being framed to further this paradigm...privacy has indeed been sacrificed to embrace the potential of the Internet and by extension, the Information Society.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 159, 'Suella Hansen'),
(84, '2008-02-05', 'The introduction of a network externality surcharge (NES) is a factor that can be included when determining termination charges, and is usually considered within the context of cost-based pricing regimes. However, the degree to which the effect of this component is felt would be a function of whether or not, and to what extent, it can be demonstrated that the introduction of such a subsidy would encourage more people to join the network.', '… in mobile markets with high penetration and coverage but with low mobile phone usage, higher estimates for network externality may result…', 'Suella Hansen', 's.hansen@strategies.nzl.com', 186, 'Suella Hansen'),
(85, '2008-01-22', NULL, 'LLU… is an important step on the ladder of investment, allowing operators to build up sufficient customer base and stability before taking on the otherwise risky business of rolling out their own infrastructure', 'Suella Hansen', 's.hansen@strategies.nzl.com', 195, 'Suella Hansen'),
(86, '2007-12-19', NULL, '… ICT is now a major economic sector, accounting for more than one-third of all exports, the major driver of Ireland’s economic revival.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 160, 'Noelle Jones'),
(87, '2007-11-27', NULL, '… Through the pooling of limited resources, a regional approach to telecommunications regulation could be beneficial to groups of smaller nations.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 187, 'Suella Hansen'),
(88, '2007-11-07', NULL, '… operators must look for innovative strategies aimed at encouraging people to make more – and longer – revenue-generating calls, particularly during offpeak times when little incremental cost is incurred. ', 'Noelle Jones', 'n.jones@strategies.nzl.com', 190, 'Noelle Jones'),
(89, '2007-05-22', 'Emerging NGN networks and services represent a fundamental change from the conventional technologies and architectures of the PSTN. Services such as NGN voice telephony reside at a higher network layer, meaning that new services and applications can be defined without considering the underlying transport and network capabilities. Not surprisingly regulators are dispensing with the old rule-books and facing up to a host of new issues.', '… regulatory policies and processes must be reviewed and adapted. Failure to act may lead to new network access bottlenecks in incumbent-controlled NGNs and potentially the end of competition in the emerging new services market.', 'Suella Hansen', 's.hansen@strategies.nzl.com', 51, 'Suella Hansen'),
(90, '2007-04-18', NULL, 'Countries such as Ireland and New Zealand have more than tripled broadband penetration since 2004. Even more striking is the continued strong growth in many of the leaders.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 174, 'Noelle Jones'),
(91, '2007-03-06', NULL, '…operators contemplating the investment decision must take a medium to long term view', 'Nicolas Tassitani', 'n.tassitani@strategies.nzl.com', 192, 'Nicolas Tassitani'),
(92, '2007-02-13', NULL, '…why is MNP a success in Australia? Quite simply, from the consumer’s viewpoint it is a quick, seamless, low-cost experience ', 'Noelle Jones', 'n.jones@strategies.nzl.com', 173, 'Noelle Jones'),
(93, '2006-10-25', 'It was disappointing to find that in some academic circles there was a complete failure to understand the main thrust of Network Strategies’ work for the Ministry of Economic Development’s Stocktake, which was to uncover what needs to happen for New Zealand broadband penetration to exceed 25% within a reasonable timeframe. In particular we considered how to achieve expanded service rollout and greater bandwidth (and thus stimulate applications and usage) at an acceptable price. While in theory such a takeup may be possible under monopolistic conditions, in practice it is highly unlikely! With no competitive or regulatory pressures to reduce prices, consumers will inevitably lose out.', '...we believe that the misunderstanding, misrepresentation and misquotation of [our] work ... is of an extremely serious nature as these errors are used to form the bases of arguments and conclusions which seek to persuade the Select Committee to follow a particular regulatory course', 'Suella Hansen', 's.hansen@strategies.nzl.com', 34, 'Suella Hansen'),
(94, '2006-08-09', 'In June 2005 New Zealand was ranked 22 out of 30 OECD countries in the OECD’s broadband penetration ranking. Despite Telecom achieving broadband rollout targets and lowering prices significantly in the intervening period, the December 2005 ranking had not changed. Why so? Simply put, New Zealand’s affordable entry level broadband packages have very limited capability and little appeal to many potential customers – partly due to the lack of competition in the New Zealand broadband market. ', '...ISPs have been complaining for years about a lack of access on reasonable terms and conditions to Telecom’s local loop', 'Suella Hansen', 's.hansen@strategies.nzl.com', 193, 'Suella Hansen'),
(95, '2006-04-19', NULL, 'Determining a ‘cost based’ price for voice on an NGN will be difficult using the conventional economic (LRIC) approach and, if implemented, may lead to pricing anomalies between voice and broadband NGN services ', 'Suella Hansen', 's.hansen@strategies.nzl.com', 172, 'Suella Hansen'),
(96, '2006-01-25', 'So Telecom New Zealand thinks that New Zealand’s lowly position (22 out of 30 countries) in the June 2005 OECD broadband penetration rankings is due to the existence of free local calling? “Free” local calling exists in Canada and the United States but it has not hindered broadband uptake there. More neutral parties including the New Zealand Communications Minister, the OECD and the president of InternetNZ agree that the real reason for New Zealand’s position in the ranking is high prices.', '...the New Zealand Government’s failure to mandate LLU...may result in NZ slipping further down the OECD ranking', 'Suella Hansen', 's.hansen@strategies.nzl.com', 194, 'Suella Hansen'),
(97, '2005-12-19', NULL, '...the market will not work effectively if consumers in a converged world are not able to move seamlessly from one service provider to another', 'Suella Hansen', 's.hansen@strategies.nzl.com', 49, 'Suella Hansen'),
(98, '2005-12-05', NULL, '...services such as e-government, e-health and e-learning have particular importance in stimulating demand for broadband services ', 'Noelle Jones', 'n.jones@strategies.nzl.com', 191, 'Noelle Jones'),
(100, '2017-06-07', 'The high cost of fibre deployment in the access network is still the main obstacle facing broadband connectivity, particularly in rural areas. Low population densities and long drop lengths do not justify the business case. However, urban areas have their challenges too. ', '...new solutions for deploying fibre cables in service water pipes promise significant cost cuts.', 'Salim Elzwawi', 's.elzwawi@strategies.nzl.com', 203, 'Salim Elzwawi'),
(101, '2017-07-10', NULL, '...many mission critical applications can be added to LTE by means of software upgrades.', 'Salim Elzwawi', 's.elzwawi@strategies.nzl.com', 218, 'Salim Elzwawi'),
(124, '2018-03-06', 'By the end of the Ultra-Fast Broadband Extension (UFB2) in 2022,  87% of New Zealand homes and businesses are expected to have access to fibre-based broadband. However, for the remaining 13% of homes in rural New Zealand the luxury of tapping in to an unlimited ultra-high speed data pipe will be out of reach, or come at a significantly higher cost.', 'In many parts of the world, moderately priced and high speed rural broadband connectivity remains a challenge.', 'Salim Elzwawi', 's.elzwawi@strategies.nzl.com', 246, 'Salim Elzwawi'),
(125, '2018-08-16', 'Eight months after the switch to digital radio in Norway, what is really happening in the radio market? Is DAB a success?', 'Audiences have declined to record low levels, with less than half of all Norwegians listening to national radio services during weeks 28 to 30 of 2018.', 'Noelle Jones', 'n.jones@strategies.nzl.com', 260, 'Noelle Jones'),
(126, '2019-02-18', 'While the potential of IoT has been demonstrated in many fields, the adoption of IoT solutions still lags the forecasts made by IoT enthusiasts at the start of the hype. For many businesses, the IoT landscape still appears to be too fragmented, with the overwhelming number of technologies, standards and platforms contributing to this perception. ', 'To unlock the full potential of IoT, a wider partnership with all internal and external stakeholders is essential to compensate for expertise gaps, cost solutions efficiently and tackle interoperability issues. ', 'Salim Elzwawi', 's.elzwawi@strategies.nzl.com', 265, 'Salim Elzwawi');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `ArticlePage`
--
ALTER TABLE `ArticlePage`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `PhotoID` (`PhotoID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `ArticlePage`
--
ALTER TABLE `ArticlePage`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=127;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
